name: Running eBPF in GitHub Action

on:
  push:
    branches: [main]

jobs:
  goaction:
    runs-on: ubuntu-latest
    steps:
      # Ubuntu 24.04 is not supporting BPF-LSM!
      #- name: Check if BPF-LSM is available
      #run: cat /boot/config-$(uname -r) | grep CONFIG_BPF_LSM && cat /sys/kernel/security/lsm
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Update action files with the new code
      uses: dorkamotorka/goaction@master
      with:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        image: dorkamotorka/ubuntu-ebpf
        path: ./app

    - name: Build a new container
      uses: docker/build-push-action@v6
      with:
        tags: dorkamotorka/ebpf-gh-action:latest
        push: true

    - name: Run container
      uses: addnab/docker-run-action@v3
      with:
          image: dorkamotorka/ebpf-gh-action:latest
          options: --detach --name ebpf-gh-action --privileged -v /sys/:/sys/ -v /tmp/:/tmp/ -v /etc/:/etc/ --pid=host --cgroupns=host -v /proc:/proc -v /boot:/boot
          run: |
            /bin/action 2>&1 | tee /tmp/output.log # Capture the output and save to a log file

    - name: Wait container to come alive
      run: |
        echo -n "Waiting for container to start..."
        while [[ "$(docker exec ebpf-gh-action curl -s -o /dev/null -w ''%{http_code}'' localhost:3377/healthz)" != "200" ]]
        do
          echo -n "Still waiting..."
          sleep 1
        done
        sleep 1

    - name: Make some dummy sycalls 
      run: |
        ls -lah
        mkdir mydir
        rm -rf mydir
        ps aux
        whoami
        uname -a

    # This data could be exported to some tool
    # but for this example we only store it as an artifact
    - name: Upload eBPF logs as artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-log
        path: /tmp/output.log
